# Generated by Django 5.0.3 on 2024-03-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_name',
            new_name='name',
        ),
    ]
