# Generated by Django 5.0.3 on 2024-03-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_material_name_material_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='material_name',
        ),
    ]
