# Generated by Django 5.0.3 on 2024-03-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_material_warehouse_material_w'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='material_w',
            new_name='material',
        ),
    ]
