# Generated by Django 5.0.3 on 2024-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
