# Generated by Django 5.0.3 on 2024-03-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productmaterial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=2000),
        ),
    ]
